### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Kyro-1** [qoft/discord-server-booster#20]
Traceback (most recent call last):
  File "C:\user\discord-server-booster-main\main.py", line 96, in <module>
    main()
  File "C:\user\discord-server-booster-main\main.py", line 87, in main
    with open("tokens.txt", "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'tokens.txt'

**Comment by Leonhart-n** [comment]
add tokens.txt file then put your user token in there , u can just use token logger to grab ppl token (make sure they have nitro)
